stages:
  - publish


Publish.Tag:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint:
    - ''
  script:
  - export TAG_MAJOR=$(echo $CI_COMMIT_TAG | cut -d. -f1)
  - export TAG_MINOR=$(echo $CI_COMMIT_TAG | cut -d. -f2)
  - export TAG_PATCH=$(echo $CI_COMMIT_TAG | cut -d. -f3)
  - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
    --destination "${CI_REGISTRY_IMAGE}:${TAG_MAJOR}"
    --destination "${CI_REGISTRY_IMAGE}:${TAG_MAJOR}.${TAG_MINOR}"
    --destination "${CI_REGISTRY_IMAGE}:${TAG_MAJOR}.${TAG_MINOR}.${TAG_PATCH}"
    --destination "${CI_REGISTRY_IMAGE}:stable"
    --build-arg THEME_GIT_COMMIT=${CI_COMMIT_SHORT_SHA}
    --build-arg THEME_GIT_TAG=${CI_COMMIT_TAG}
  rules:
  - if: $CI_COMMIT_TAG

Publish.Nightly:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint:
    - ''
  script:
  - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
    --destination "${CI_REGISTRY_IMAGE}:nightly"
    --build-arg THEME_GIT_COMMIT=${CI_COMMIT_SHORT_SHA}
    --build-arg THEME_GIT_TAG=nightly
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
