.TH "pixelcatproductions/class/crisp Directory Reference" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixelcatproductions/class/crisp Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBapi\fP"
.br
.ti -1c
.RI "directory \fBcore\fP"
.br
.ti -1c
.RI "directory \fBexceptions\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBUniverse\&.php\fP"
.br
.in -1c
