.TH "Migrations" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Migrations
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBisMigrated\fP (string $file)"
.br
.ti -1c
.RI "\fBmigrate\fP (string $Dir=__DIR__ \&. '/\&.\&./', string $\fBPlugin\fP=null)"
.br
.ti -1c
.RI "\fBcreate\fP (string $MigrationName, string $Dir=__DIR__ \&. '/\&.\&./')"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBDB_VARCHAR\fP = 'varchar(255)'"
.br
.ti -1c
.RI "const \fBDB_TEXT\fP = 'text'"
.br
.ti -1c
.RI "const \fBDB_INTEGER\fP = 'integer'"
.br
.ti -1c
.RI "const \fBDB_TIMESTAMP\fP = 'datetime'"
.br
.ti -1c
.RI "const \fBDB_BOOL\fP = 'tinyint(1)'"
.br
.ti -1c
.RI "const \fBDB_LONGTEXT\fP = 'LONGTEXT'"
.br
.ti -1c
.RI "const \fBDB_PRIMARYKEY\fP = 'PRIMARY'"
.br
.ti -1c
.RI "const \fBDB_UNIQUEKEY\fP = 'UNIQUE'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBbegin\fP ()"
.br
.ti -1c
.RI "\fBrollback\fP ()"
.br
.ti -1c
.RI "\fBend\fP ()"
.br
.ti -1c
.RI "\fBaddIndex\fP (string $Table, string $Column, $Type=self::DB_PRIMARYKEY, string $IndexName=null)"
.br
.ti -1c
.RI "\fBdropColumn\fP (string $Table, string $Column)"
.br
.ti -1c
.RI "\fBaddColumn\fP (string $Table, array $Column)"
.br
.ti -1c
.RI "\fBcreateTable\fP (string $Table,\&.\&.\&. $Columns)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "PDO \fB$Database\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Crisp DB Migration Class 
.PP
\fBSince\fP
.RS 4
0\&.0\&.8-beta\&.RC1 
.RE
.PP

.PP
Definition at line 26 of file Migrations\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"

.PP
Definition at line 47 of file Migrations\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addColumn (string $Table, array $Column)\fC [protected]\fP"
Add a column to a table 
.PP
\fBParameters\fP
.RS 4
\fI$Table\fP The table name 
.br
\fI$Column\fP An array consisting of the column name, column type and additional info, e\&.g\&. array('ColName, self::DB_VARCHAR, 'NOT NULL") 
.RE
.PP
\fBReturns\fP
.RS 4
boolean 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 261 of file Migrations\&.php\&.
.SS "addIndex (string $Table, string $Column,  $Type = \fCself::DB_PRIMARYKEY\fP, string $IndexName = \fCnull\fP)\fC [protected]\fP"
Create a new index for a table 
.PP
\fBParameters\fP
.RS 4
\fI$Table\fP The name of the table 
.br
\fI$Column\fP The name of the column 
.br
\fI$Type\fP The type of the index 
.br
\fI$IndexName\fP The name of the index, Unused if PRIMARYKEY 
.RE
.PP
\fBReturns\fP
.RS 4
boolean 
.RE
.PP
\fBSince\fP
.RS 4
0\&.0\&.8-beta\&.RC2 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 212 of file Migrations\&.php\&.
.SS "begin ()\fC [protected]\fP"
Begin a \fBMySQL\fP Transaction 
.PP
\fBSince\fP
.RS 4
0\&.0\&.8-beta\&.RC2 
.RE
.PP
\fBReturns\fP
.RS 4
boolean 
.RE
.PP

.PP
Definition at line 57 of file Migrations\&.php\&.
.SS "create (string $MigrationName, string $Dir = \fC__DIR__ \&. '/\&.\&./'\fP)"
Create a new migration file\&. 
.PP
\fBParameters\fP
.RS 4
\fI$MigrationName\fP The name of the migration, only Alpha Letters\&. 
.br
\fI$Dir\fP The base directory to look for migrations\&. e\&.g Setting 'plugin' will create one in 'plugin/migrations' 
.RE
.PP
\fBSince\fP
.RS 4
0\&.0\&.8-beta\&.RC2 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 182 of file Migrations\&.php\&.
.SS "createTable (string $Table,  $Columns)\fC [protected]\fP"
Create a new table\&. This function accepts infinite parameters to add columns 
.PP
\fBParameters\fP
.RS 4
\fI$Table\fP The table name 
.br
\fImixed\fP \&.\&.\&.$Columns An array consisting of the column name, column type and additional info, e\&.g\&. array('ColName, self::DB_VARCHAR, 'NOT NULL") 
.RE
.PP
\fBReturns\fP
.RS 4
boolean 
.RE
.PP
\fBSince\fP
.RS 4
0\&.0\&.8-beta\&.RC2 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 283 of file Migrations\&.php\&.
.SS "dropColumn (string $Table, string $Column)\fC [protected]\fP"
Remove a column from a table 
.PP
\fBParameters\fP
.RS 4
\fI$Table\fP The table name 
.br
\fI$Column\fP The name of the column 
.RE
.PP
\fBReturns\fP
.RS 4
boolean 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 239 of file Migrations\&.php\&.
.SS "end ()\fC [protected]\fP"
End/commit a \fBMySQL\fP Transaction 
.PP
\fBSince\fP
.RS 4
0\&.0\&.8-beta\&.RC2 
.RE
.PP
\fBReturns\fP
.RS 4
boolean 
.RE
.PP

.PP
Definition at line 87 of file Migrations\&.php\&.
.SS "isMigrated (string $file)"
Check if a migration is already installed 
.PP
\fBParameters\fP
.RS 4
\fI$file\fP The migration filename to check\&. Don't use the extension in the filename\&. 
.RE
.PP
\fBSee also\fP
.RS 4
basename 
.RE
.PP
\fBSince\fP
.RS 4
0\&.0\&.8-beta\&.RC2 
.RE
.PP
\fBReturns\fP
.RS 4
boolean 
.RE
.PP

.PP
Definition at line 104 of file Migrations\&.php\&.
.SS "migrate (string $Dir = \fC__DIR__ \&. '/\&.\&./'\fP, string $Plugin = \fCnull\fP)"
Begin the migration of the database 
.PP
\fBSince\fP
.RS 4
0\&.0\&.8-beta\&.RC2 
.RE
.PP
\fBParameters\fP
.RS 4
\fI$Dir\fP The directory base to look for migrations\&. e\&.g Setting 'plugin' will look in 'plugin/migrations' 
.br
\fI$Plugin\fP If the migration has been done for a plugin, this is the name 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 123 of file Migrations\&.php\&.
.SS "rollback ()\fC [protected]\fP"
Rollback a \fBMySQL\fP Transaction 
.PP
\fBSince\fP
.RS 4
0\&.0\&.8-beta\&.RC2 
.RE
.PP
\fBReturns\fP
.RS 4
boolean 
.RE
.PP

.PP
Definition at line 72 of file Migrations\&.php\&.
.SH "Field Documentation"
.PP 
.SS "PDO $Database\fC [protected]\fP"

.PP
Definition at line 32 of file Migrations\&.php\&.
.SS "const DB_BOOL = 'tinyint(1)'"

.PP
Definition at line 40 of file Migrations\&.php\&.
.SS "const DB_INTEGER = 'integer'"

.PP
Definition at line 38 of file Migrations\&.php\&.
.SS "const DB_LONGTEXT = 'LONGTEXT'"

.PP
Definition at line 41 of file Migrations\&.php\&.
.SS "const DB_PRIMARYKEY = 'PRIMARY'"

.PP
Definition at line 44 of file Migrations\&.php\&.
.SS "const DB_TEXT = 'text'"

.PP
Definition at line 37 of file Migrations\&.php\&.
.SS "const DB_TIMESTAMP = 'datetime'"

.PP
Definition at line 39 of file Migrations\&.php\&.
.SS "const DB_UNIQUEKEY = 'UNIQUE'"

.PP
Definition at line 45 of file Migrations\&.php\&.
.SS "const DB_VARCHAR = 'varchar(255)'"

.PP
Definition at line 36 of file Migrations\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
