.TH "crisp\core" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crisp\core
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBConfig\fP"
.br
.ti -1c
.RI "class \fBCrypto\fP"
.br
.ti -1c
.RI "class \fBMigrations\fP"
.br
.ti -1c
.RI "class \fBMySQL\fP"
.br
.ti -1c
.RI "class \fBPlugin\fP"
.br
.ti -1c
.RI "class \fBPluginAPI\fP"
.br
.ti -1c
.RI "class \fBPlugins\fP"
.br
.ti -1c
.RI "class \fBPostgres\fP"
.br
.ti -1c
.RI "class \fBRedis\fP"
.br
.ti -1c
.RI "class \fBTheme\fP"
.br
.ti -1c
.RI "class \fBThemes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
