.TH "Crypto" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Crypto
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBUUIDv4\fP ($Prefix=null, $Bytes=16)"
.br
.ti -1c
.RI "static \fBencrypt\fP ($plaintext, $encoding=null)"
.br
.ti -1c
.RI "static \fBdecrypt\fP ($ciphertext, $encoding=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interact with the encryption system behind LophotenCMS 
.PP
Definition at line 25 of file Crypto\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static decrypt ( $ciphertext,  $encoding = \fCnull\fP)\fC [static]\fP"

.PP
Definition at line 46 of file Crypto\&.php\&.
.SS "static encrypt ( $plaintext,  $encoding = \fCnull\fP)\fC [static]\fP"

.PP
Definition at line 39 of file Crypto\&.php\&.
.SS "static UUIDv4 ( $Prefix = \fCnull\fP,  $Bytes = \fC16\fP)\fC [static]\fP"

.PP
Definition at line 33 of file Crypto\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
