.TH "Theme" 3 "Sat Dec 26 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Theme
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($TwigTheme, $CurrentFile, $CurrentPage)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBaddtoNavbar\fP ($ID, $Text, $Link, $Target='_self', $Order=0, $Placement='left')"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$CurrentFile\fP"
.br
.ti -1c
.RI "\fB$CurrentPage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used internally, plugin loader 
.PP
Definition at line 26 of file Theme\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $TwigTheme,  $CurrentFile,  $CurrentPage)"
Load a theme page 
.PP
\fBParameters\fP
.RS 4
\fI$TwigTheme\fP The twig theme component 
.br
\fI$CurrentFile\fP The current file, \fBFILE\fP 
.br
\fI$CurrentPage\fP The current page template to render 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 59 of file Theme\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static addtoNavbar ( $ID,  $Text,  $Link,  $Target = \fC'_self'\fP,  $Order = \fC0\fP,  $Placement = \fC'left'\fP)\fC [static]\fP"

.PP
Definition at line 34 of file Theme\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$CurrentFile"

.PP
Definition at line 31 of file Theme\&.php\&.
.SS "$CurrentPage"

.PP
Definition at line 32 of file Theme\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
