.TH "Theme" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Theme
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($TwigTheme, $CurrentFile, $CurrentPage)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBaddtoNavbar\fP ($ID, $Text, $Link, $Target='_self', $Order=0, $Placement='left')"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$CurrentFile\fP"
.br
.ti -1c
.RI "\fB$CurrentPage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used internally, plugin loader 
.PP
Definition at line 26 of file Theme\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $TwigTheme,  $CurrentFile,  $CurrentPage)"
Load a theme page 
.PP
\fBParameters\fP
.RS 4
\fI$TwigTheme\fP The twig theme component 
.br
\fI$CurrentFile\fP The current file, \fBFILE\fP 
.br
\fI$CurrentPage\fP The current page template to render 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 70 of file Theme\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static addtoNavbar ( $ID,  $Text,  $Link,  $Target = \fC'_self'\fP,  $Order = \fC0\fP,  $Placement = \fC'left'\fP)\fC [static]\fP"
Add an item to the theme's navigation bar 
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP Unique string to identify the item 
.br
\fI$Text\fP The HTML of the navbar item 
.br
\fI$Link\fP The Link of the navbar item 
.br
\fI$Target\fP HTML a=target 
.br
\fI$Order\fP The order to appear on the navbar 
.br
\fI$Placement\fP Placed left or right of the navbar if supported by theme 
.RE
.PP
\fBSee also\fP
.RS 4
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#target Link Target 
.RE
.PP
\fBReturns\fP
.RS 4
boolean 
.RE
.PP

.PP
Definition at line 45 of file Theme\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$CurrentFile"

.PP
Definition at line 31 of file Theme\&.php\&.
.SS "$CurrentPage"

.PP
Definition at line 32 of file Theme\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
