.TH "Languages" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Languages
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLanguage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBfetchLanguages\fP ($FetchIntoClass=true)"
.br
.ti -1c
.RI "static \fBcreateLanguage\fP (string $Name, string $Code, string $NativeName, string $Flag, bool $Enabled=true)"
.br
.ti -1c
.RI "static \fBgetLanguageByCode\fP ($Code, $FetchIntoClass=true)"
.br
.ti -1c
.RI "static \fBgetLanguageByID\fP ($ID, $FetchIntoClass=true)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interact with all languages stored on the server 
.PP
Definition at line 30 of file Languages\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"

.PP
Definition at line 34 of file Languages\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static createLanguage (string $Name, string $Code, string $NativeName, string $Flag, bool $Enabled = \fCtrue\fP)\fC [static]\fP"
Create a new language 
.PP
\fBParameters\fP
.RS 4
\fI$Name\fP The name of the language 
.br
\fI$Code\fP The letter code of the language e\&.g\&. en-US, de, es, ru 
.br
\fI$NativeName\fP How is the language called in the native tongue? 
.br
\fI$Flag\fP Path to the flag image on the server 
.br
\fI$Enabled\fP Enable/disable the language 
.RE
.PP
\fBReturns\fP
.RS 4
bool TRUE if action was successful 
.RE
.PP

.PP
Definition at line 75 of file Languages\&.php\&.
.SS "static fetchLanguages ( $FetchIntoClass = \fCtrue\fP)\fC [static]\fP"
Fetches all languages 
.PP
\fBParameters\fP
.RS 4
\fI$FetchIntoClass\fP Should we fetch the result into new \\crisp\\api\\Language()? 
.RE
.PP
\fBReturns\fP
.RS 4
bool|array|\\crisp\\api\\Language with all languages 
.RE
.PP

.PP
Definition at line 48 of file Languages\&.php\&.
.SS "static getLanguageByCode ( $Code,  $FetchIntoClass = \fCtrue\fP)\fC [static]\fP"
Fetches a language by country code 
.PP
\fBParameters\fP
.RS 4
\fI$Code\fP The language's country code 
.br
\fI$FetchIntoClass\fP Should we fetch the result into new \\crisp\\api\\Language()? 
.RE
.PP
\fBReturns\fP
.RS 4
bool|\\crisp\\api\\Language|array with the language 
.RE
.PP

.PP
Definition at line 113 of file Languages\&.php\&.
.SS "static getLanguageByID ( $ID,  $FetchIntoClass = \fCtrue\fP)\fC [static]\fP"
Fetches a language by ID 
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The database ID of the language 
.br
\fItype\fP Should we fetch the result into new \\crisp\\api\\Language()? 
.RE
.PP
\fBReturns\fP
.RS 4
bool|\\crisp\\api\\Language|array with the language 
.RE
.PP

.PP
Definition at line 146 of file Languages\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
