.TH "Translation" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Translation
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($\fBLanguage\fP=null)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBlistLanguages\fP ($FetchIntoClass=true)"
.br
.ti -1c
.RI "static \fBlistTranslations\fP ()"
.br
.ti -1c
.RI "static \fBfetchAll\fP ()"
.br
.ti -1c
.RI "static \fBfetchAllByKey\fP ($Key)"
.br
.ti -1c
.RI "static \fBexists\fP ($Key)"
.br
.ti -1c
.RI "static \fBfetch\fP ($Key, $Count=1, $UserOptions=array())"
.br
.ti -1c
.RI "static \fBget\fP ($Key, $UserOptions=array())"
.br
.ti -1c
.RI "static \fBgetPlural\fP ($Key, $UserOptions=array())"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fB$Language\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
Access the translations of the CMS 
.PP
Definition at line 30 of file Translation\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $Language = \fCnull\fP)"
Sets the language code and inits the database connection for further use of functions in this class 
.PP
\fBParameters\fP
.RS 4
\fI$Language\fP The \fBLanguage\fP code or null 
.RE
.PP

.PP
Definition at line 43 of file Translation\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static exists ( $Key)\fC [static]\fP"
Check if a translation exists by key 
.PP
\fBParameters\fP
.RS 4
\fI$Key\fP The translation key 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 146 of file Translation\&.php\&.
.SS "static fetch ( $Key,  $Count = \fC1\fP,  $UserOptions = \fCarray()\fP)\fC [static]\fP"
Fetches translations for the specified key 
.PP
\fBParameters\fP
.RS 4
\fI$Key\fP The translation key 
.br
\fI$Count\fP Used for the plural and singular retrieval of translations, also exposes {{ count }} in templates\&. 
.br
\fI$UserOptions\fP Custom array used for templating 
.RE
.PP
\fBReturns\fP
.RS 4
string The translation or the key if it doesn't exist 
.RE
.PP

.PP
Definition at line 162 of file Translation\&.php\&.
.SS "static fetchAll ()\fC [static]\fP"
Retrieves all translations for the specified self::$Language @uses self::$Language 
.PP
\fBReturns\fP
.RS 4
array containing all translations for the self::$Language 
.RE
.PP

.PP
Definition at line 86 of file Translation\&.php\&.
.SS "static fetchAllByKey ( $Key)\fC [static]\fP"
Fetch all translations by key 
.PP
\fBParameters\fP
.RS 4
\fI$Key\fP The letter code 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 115 of file Translation\&.php\&.
.SS "static get ( $Key,  $UserOptions = \fCarray()\fP)\fC [static]\fP"
Fetches all singular translations for the specified key 
.PP
\fBParameters\fP
.RS 4
\fI$Key\fP The translation key 
.br
\fI$UserOptions\fP Custom array used for templating 
.RE
.PP
\fBSee also\fP
.RS 4
\fBfetch\fP 
.PP
\fBgetPlural\fP 
.RE
.PP
\fBReturns\fP
.RS 4
string The translation or the key if it doesn't exist 
.RE
.PP

.PP
Definition at line 187 of file Translation\&.php\&.
.SS "static getPlural ( $Key,  $UserOptions = \fCarray()\fP)\fC [static]\fP"
Fetches all plural translations for the specified key 
.PP
\fBParameters\fP
.RS 4
\fI$Key\fP The translation key 
.br
\fI$UserOptions\fP Custom array used for templating 
.RE
.PP
\fBSee also\fP
.RS 4
\fBfetch\fP 
.PP
\fBget\fP 
.RE
.PP
\fBReturns\fP
.RS 4
string The translation or the key if it doesn't exist 
.RE
.PP

.PP
Definition at line 233 of file Translation\&.php\&.
.SS "static listLanguages ( $FetchIntoClass = \fCtrue\fP)\fC [static]\fP"
Same as \\crisp\\api\\lists\\Languages()->fetchLanguages() @uses \\crisp\\api\\lists\\Languages() 
.PP
\fBParameters\fP
.RS 4
\fI$FetchIntoClass\fP Should the result be fetched into a \\crisp\\api\\Language class 
.RE
.PP
\fBReturns\fP
.RS 4
\\crisp\\api\\Language|array depending on the $FetchIntoClass parameter 
.RE
.PP

.PP
Definition at line 61 of file Translation\&.php\&.
.SS "static listTranslations ()\fC [static]\fP"
Retrieves all translations with key and language code 
.PP
\fBReturns\fP
.RS 4
array containing all translations on the server 
.RE
.PP

.PP
Definition at line 70 of file Translation\&.php\&.
.SH "Field Documentation"
.PP 
.SS "string $\fBLanguage\fP = null\fC [static]\fP"

.PP
Definition at line 36 of file Translation\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
