.TH "Themes" 3 "Sat Dec 26 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Themes
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBclearCache\fP ()"
.br
.ti -1c
.RI "static \fBload\fP ($TwigTheme, $CurrentFile, $CurrentPage)"
.br
.ti -1c
.RI "static \fBrefreshTranslations\fP ($ThemeMetadata)"
.br
.ti -1c
.RI "static \fBrefreshKVStorage\fP ($ThemeMetadata)"
.br
.ti -1c
.RI "static \fBinstallKVStorage\fP ($ThemeMetadata)"
.br
.ti -1c
.RI "static \fBinstallTranslations\fP ($ThemeMetadata)"
.br
.ti -1c
.RI "static \fBisInstalled\fP ($ThemeName)"
.br
.ti -1c
.RI "static \fBisValid\fP ($ThemeName)"
.br
.ti -1c
.RI "static \fBuninstall\fP ($ThemeName)"
.br
.ti -1c
.RI "static \fBdeleteData\fP ($ThemeName)"
.br
.ti -1c
.RI "static \fBreinstall\fP ($ThemeName)"
.br
.ti -1c
.RI "static \fBgetThemeMetadata\fP ($ThemeName)"
.br
.ti -1c
.RI "static \fBuninstallKVStorage\fP ($ThemeMetadata)"
.br
.ti -1c
.RI "static \fBuninstallTranslations\fP ($ThemeMetadata)"
.br
.ti -1c
.RI "static \fBinstall\fP ($ThemeName)"
.br
.ti -1c
.RI "static \fBregisterUninstallHook\fP ($ThemeName, $Function)"
.br
.ti -1c
.RI "static \fBregisterInstallHook\fP ($ThemeName, $Function)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used internally, theme loader 
.PP
Definition at line 26 of file Themes\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static clearCache ()\fC [static]\fP"
Clear the theme cache 
.PP
\fBReturns\fP
.RS 4
boolean 
.RE
.PP

.PP
Definition at line 34 of file Themes\&.php\&.
.SS "static deleteData ( $ThemeName)\fC [static]\fP"
Deletes all KVStorage Items from the \fBPlugin\fP
.PP
If the theme is installed, it will get uninstalled first 
.PP
\fBParameters\fP
.RS 4
\fI$ThemeName\fP The folder name of the theme 
.RE
.PP
\fBReturns\fP
.RS 4
boolean TRUE if the data has been successfully deleted 
.RE
.PP

.PP
Definition at line 194 of file Themes\&.php\&.
.SS "static getThemeMetadata ( $ThemeName)\fC [static]\fP"

.PP
Definition at line 220 of file Themes\&.php\&.
.SS "static install ( $ThemeName)\fC [static]\fP"

.PP
Definition at line 265 of file Themes\&.php\&.
.SS "static installKVStorage ( $ThemeMetadata)\fC [static]\fP"

.PP
Definition at line 85 of file Themes\&.php\&.
.SS "static installTranslations ( $ThemeMetadata)\fC [static]\fP"

.PP
Definition at line 104 of file Themes\&.php\&.
.SS "static isInstalled ( $ThemeName)\fC [static]\fP"
Checks if the specified theme is installed 
.PP
\fBParameters\fP
.RS 4
\fI$ThemeName\fP The folder name of the theme 
.RE
.PP
\fBReturns\fP
.RS 4
boolean TRUE if theme is installed, otherwise FALSE 
.RE
.PP

.PP
Definition at line 135 of file Themes\&.php\&.
.SS "static isValid ( $ThemeName)\fC [static]\fP"

.PP
Definition at line 139 of file Themes\&.php\&.
.SS "static load ( $TwigTheme,  $CurrentFile,  $CurrentPage)\fC [static]\fP"

.PP
Definition at line 48 of file Themes\&.php\&.
.SS "static refreshKVStorage ( $ThemeMetadata)\fC [static]\fP"

.PP
Definition at line 80 of file Themes\&.php\&.
.SS "static refreshTranslations ( $ThemeMetadata)\fC [static]\fP"

.PP
Definition at line 75 of file Themes\&.php\&.
.SS "static registerInstallHook ( $ThemeName,  $Function)\fC [static]\fP"
Registers an install hook for your theme\&. 
.PP
\fBParameters\fP
.RS 4
\fI$ThemeName\fP 
.br
\fI$Function\fP Callback function, either anonymous or a string to a function 
.RE
.PP
\fBReturns\fP
.RS 4
boolean TRUE if hook could be registered, otherwise false 
.RE
.PP

.PP
Definition at line 312 of file Themes\&.php\&.
.SS "static registerUninstallHook ( $ThemeName,  $Function)\fC [static]\fP"
Registers an uninstall hook for your theme\&. 
.PP
\fBParameters\fP
.RS 4
\fI$ThemeName\fP 
.br
\fI$Function\fP Callback function, either anonymous or a string to a function 
.RE
.PP
\fBReturns\fP
.RS 4
boolean TRUE if hook could be registered, otherwise false 
.RE
.PP

.PP
Definition at line 298 of file Themes\&.php\&.
.SS "static reinstall ( $ThemeName)\fC [static]\fP"

.PP
Definition at line 213 of file Themes\&.php\&.
.SS "static uninstall ( $ThemeName)\fC [static]\fP"

.PP
Definition at line 144 of file Themes\&.php\&.
.SS "static uninstallKVStorage ( $ThemeMetadata)\fC [static]\fP"

.PP
Definition at line 230 of file Themes\&.php\&.
.SS "static uninstallTranslations ( $ThemeMetadata)\fC [static]\fP"

.PP
Definition at line 242 of file Themes\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
