.TH "InvalidLanguageException" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvalidLanguageException
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message, $code=0, Exception $previous=null)"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception to throw when the setEmail method fails because of a malformed email
.PP
\fBAuthor\fP
.RS 4
Justin René Back jback@pixelcatproductions.net 
.RE
.PP

.PP
Definition at line 27 of file InvalidLanguageException\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message,  $code = \fC0\fP, Exception $previous = \fCnull\fP)"

.PP
Definition at line 29 of file InvalidLanguageException\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__toString ()"

.PP
Definition at line 33 of file InvalidLanguageException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
