.TH "Phoenix" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Phoenix
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgenerateApiFiles\fP (string $ID)"
.br
.ti -1c
.RI "static \fBgetPointsByServicePG\fP (string $ID)"
.br
.ti -1c
.RI "static \fBgetDocumentsByServicePG\fP (string $ID)"
.br
.ti -1c
.RI "static \fBgetPointsPG\fP ()"
.br
.ti -1c
.RI "static \fBgetPointPG\fP (string $ID)"
.br
.ti -1c
.RI "static \fBgetPoint\fP (string $ID, bool $Force=false)"
.br
.ti -1c
.RI "static \fBgetCasePG\fP (string $ID)"
.br
.ti -1c
.RI "static \fBgetCase\fP (string $ID, bool $Force=false)"
.br
.ti -1c
.RI "static \fBgetTopicPG\fP (string $ID)"
.br
.ti -1c
.RI "static \fBgetTopic\fP (string $ID, bool $Force=false)"
.br
.ti -1c
.RI "static \fBgetServiceByName\fP (string $Name, bool $Force=false)"
.br
.ti -1c
.RI "static \fBsearchServiceByNamePG\fP (string $Name)"
.br
.ti -1c
.RI "static \fBgetServiceBySlugPG\fP (string $Name)"
.br
.ti -1c
.RI "static \fBgetServiceByNamePG\fP (string $Name)"
.br
.ti -1c
.RI "static \fBserviceExistsBySlugPG\fP (string $Name)"
.br
.ti -1c
.RI "static \fBserviceExistsByNamePG\fP (string $Name)"
.br
.ti -1c
.RI "static \fBserviceExistsByName\fP (string $Name)"
.br
.ti -1c
.RI "static \fBpointExists\fP (string $ID)"
.br
.ti -1c
.RI "static \fBpointExistsPG\fP (string $ID)"
.br
.ti -1c
.RI "static \fBserviceExistsPG\fP (string $ID)"
.br
.ti -1c
.RI "static \fBserviceExists\fP (string $ID)"
.br
.ti -1c
.RI "static \fBgetServicePG\fP (string $ID)"
.br
.ti -1c
.RI "static \fBgetService\fP (string $ID, bool $Force=false)"
.br
.ti -1c
.RI "static \fBgetTopicsPG\fP ()"
.br
.ti -1c
.RI "static \fBgetTopics\fP (bool $Force=false)"
.br
.ti -1c
.RI "static \fBgetCasesPG\fP ()"
.br
.ti -1c
.RI "static \fBgetCases\fP (bool $Force=false)"
.br
.ti -1c
.RI "static \fBgetServicesPG\fP ()"
.br
.ti -1c
.RI "static \fBgetServices\fP (bool $Force=false)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Some useful phoenix functions 
.PP
Definition at line 25 of file Phoenix\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static generateApiFiles (string $ID)\fC [static]\fP"
Generates tosdr\&.org api data from a service id 
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The service ID from \fBPhoenix\fP to generate the API Files from 
.RE
.PP
\fBReturns\fP
.RS 4
array The API data 
.RE
.PP

.PP
Definition at line 45 of file Phoenix\&.php\&.
.SS "static getCase (string $ID, bool $Force = \fCfalse\fP)\fC [static]\fP"
Get details of a case 
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The ID of a case 
.br
\fI$Force\fP Force update from \fBPhoenix\fP 
.RE
.PP
\fBReturns\fP
.RS 4
object 
.RE
.PP
\fBDeprecated\fP
.RS 4
Use \fBPhoenix::getCasePG\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 322 of file Phoenix\&.php\&.
.SS "static getCasePG (string $ID)\fC [static]\fP"
Gets details about a case from postgres 
.PP
\fBSee also\fP
.RS 4
https://github.com/tosdr/edit.tosdr.org/blob/8b900bf8879b8ed3a4a2a6bbabbeafa7d2ab540c/db/schema.rb#L42-L52 Database Schema 
.RE
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The id of a case 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 289 of file Phoenix\&.php\&.
.SS "static getCases (bool $Force = \fCfalse\fP)\fC [static]\fP"
Get a list of cases 
.PP
\fBParameters\fP
.RS 4
\fI$Force\fP Force update from phoenix 
.RE
.PP
\fBReturns\fP
.RS 4
object 
.RE
.PP
\fBDeprecated\fP
.RS 4
Use \fBPhoenix::getCasesPG\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 927 of file Phoenix\&.php\&.
.SS "static getCasesPG ()\fC [static]\fP"
List all cases from postgres 
.PP
\fBSee also\fP
.RS 4
https://github.com/tosdr/edit.tosdr.org/blob/8b900bf8879b8ed3a4a2a6bbabbeafa7d2ab540c/db/schema.rb#L42-L52 Database Schema 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 900 of file Phoenix\&.php\&.
.SS "static getDocumentsByServicePG (string $ID)\fC [static]\fP"
Get all documents by a service from postgres 
.PP
\fBSee also\fP
.RS 4
https://github.com/tosdr/edit.tosdr.org/blob/8b900bf8879b8ed3a4a2a6bbabbeafa7d2ab540c/db/schema.rb#L64-L77 Database Schema 
.RE
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The Service ID 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 158 of file Phoenix\&.php\&.
.SS "static getPoint (string $ID, bool $Force = \fCfalse\fP)\fC [static]\fP"
Get details of a point from phoenix 
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The ID of the point 
.br
\fI$Force\fP Force update from phoenix 
.RE
.PP
\fBReturns\fP
.RS 4
object 
.RE
.PP
\fBDeprecated\fP
.RS 4
Use \fBPhoenix::getPointPG\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 245 of file Phoenix\&.php\&.
.SS "static getPointPG (string $ID)\fC [static]\fP"
Gets details about a point from postgres 
.PP
\fBSee also\fP
.RS 4
https://github.com/tosdr/edit.tosdr.org/blob/8b900bf8879b8ed3a4a2a6bbabbeafa7d2ab540c/db/schema.rb#L89-L111 Database Schema 
.RE
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The ID of a point 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 213 of file Phoenix\&.php\&.
.SS "static getPointsByServicePG (string $ID)\fC [static]\fP"
Retrieve points by a service from postgres 
.PP
\fBSee also\fP
.RS 4
https://github.com/tosdr/edit.tosdr.org/blob/8b900bf8879b8ed3a4a2a6bbabbeafa7d2ab540c/db/schema.rb#L89-L111 Database Schema 
.RE
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The ID of the Service 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 124 of file Phoenix\&.php\&.
.SS "static getPointsPG ()\fC [static]\fP"
List all points from postgres 
.PP
\fBSee also\fP
.RS 4
https://github.com/tosdr/edit.tosdr.org/blob/8b900bf8879b8ed3a4a2a6bbabbeafa7d2ab540c/db/schema.rb#L89-L111 Database Schema 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 187 of file Phoenix\&.php\&.
.SS "static getService (string $ID, bool $Force = \fCfalse\fP)\fC [static]\fP"
Get details of a service by name 
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The ID of a service 
.br
\fI$Force\fP Force update from phoenix 
.RE
.PP
\fBReturns\fP
.RS 4
object 
.RE
.PP
\fBDeprecated\fP
.RS 4
Use \fBPhoenix::getServicePG\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 773 of file Phoenix\&.php\&.
.SS "static getServiceByName (string $Name, bool $Force = \fCfalse\fP)\fC [static]\fP"
Get details of a service by name 
.PP
\fBParameters\fP
.RS 4
\fI$Name\fP The name of the service 
.br
\fI$Force\fP Force update from phoenix 
.RE
.PP
\fBReturns\fP
.RS 4
object 
.RE
.PP
\fBDeprecated\fP
.RS 4
Use \fBPhoenix::getServiceByNamePG\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 444 of file Phoenix\&.php\&.
.SS "static getServiceByNamePG (string $Name)\fC [static]\fP"
Get details of a service via postgres by name 
.PP
\fBSee also\fP
.RS 4
https://github.com/tosdr/edit.tosdr.org/blob/8b900bf8879b8ed3a4a2a6bbabbeafa7d2ab540c/db/schema.rb#L134-L148 Database Schema 
.RE
.PP
\fBParameters\fP
.RS 4
\fI$Name\fP the exact name of the service 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 543 of file Phoenix\&.php\&.
.SS "static getServiceBySlugPG (string $Name)\fC [static]\fP"
Get details of a service from postgres via a slug 
.PP
\fBSee also\fP
.RS 4
https://github.com/tosdr/edit.tosdr.org/blob/8b900bf8879b8ed3a4a2a6bbabbeafa7d2ab540c/db/schema.rb#L134-L148 Database Schema 
.RE
.PP
\fBParameters\fP
.RS 4
\fI$Name\fP The slug of a service 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 513 of file Phoenix\&.php\&.
.SS "static getServicePG (string $ID)\fC [static]\fP"

.PP
Definition at line 733 of file Phoenix\&.php\&.
.SS "static getServices (bool $Force = \fCfalse\fP)\fC [static]\fP"
Get a list of services 
.PP
\fBParameters\fP
.RS 4
\fI$Force\fP Force update from phoenix 
.RE
.PP
\fBReturns\fP
.RS 4
object 
.RE
.PP
\fBDeprecated\fP
.RS 4
Please use \fBPhoenix::getServicesPG\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 998 of file Phoenix\&.php\&.
.SS "static getServicesPG ()\fC [static]\fP"
List all services from postgres 
.PP
\fBSee also\fP
.RS 4
https://github.com/tosdr/edit.tosdr.org/blob/8b900bf8879b8ed3a4a2a6bbabbeafa7d2ab540c/db/schema.rb#L134-L148 Database Schema 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 971 of file Phoenix\&.php\&.
.SS "static getTopic (string $ID, bool $Force = \fCfalse\fP)\fC [static]\fP"
Get details of a topic 
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The topic id 
.br
\fI$Force\fP Force update from phoenix 
.RE
.PP
\fBReturns\fP
.RS 4
object 
.RE
.PP
\fBDeprecated\fP
.RS 4
Use \fBPhoenix::getTopicPG\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 398 of file Phoenix\&.php\&.
.SS "static getTopicPG (string $ID)\fC [static]\fP"
Gets details about a topic from postgres 
.PP
\fBSee also\fP
.RS 4
https://github.com/tosdr/edit.tosdr.org/blob/8b900bf8879b8ed3a4a2a6bbabbeafa7d2ab540c/db/schema.rb#L170-L177 Database Schema 
.RE
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The topic id 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 366 of file Phoenix\&.php\&.
.SS "static getTopics (bool $Force = \fCfalse\fP)\fC [static]\fP"
Get a list of topics 
.PP
\fBParameters\fP
.RS 4
\fI$Force\fP Force update from phoenix 
.RE
.PP
\fBReturns\fP
.RS 4
object 
.RE
.PP
\fBDeprecated\fP
.RS 4
Use \fBPhoenix::getServicesPG\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 857 of file Phoenix\&.php\&.
.SS "static getTopicsPG ()\fC [static]\fP"
List all topics from postgres 
.PP
\fBSee also\fP
.RS 4
https://github.com/tosdr/edit.tosdr.org/blob/8b900bf8879b8ed3a4a2a6bbabbeafa7d2ab540c/db/schema.rb#L170-L177 Database Schema 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 830 of file Phoenix\&.php\&.
.SS "static pointExists (string $ID)\fC [static]\fP"
Check if the point exists by name 
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The ID of the point 
.RE
.PP
\fBDeprecated\fP
.RS 4
Use \fBPhoenix::pointExistsPG\fP 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 653 of file Phoenix\&.php\&.
.SS "static pointExistsPG (string $ID)\fC [static]\fP"
Check if a point exists from postgres via slug 
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The id of the point 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 666 of file Phoenix\&.php\&.
.SS "static searchServiceByNamePG (string $Name)\fC [static]\fP"
Search for a service via postgres 
.PP
\fBSee also\fP
.RS 4
https://github.com/tosdr/edit.tosdr.org/blob/8b900bf8879b8ed3a4a2a6bbabbeafa7d2ab540c/db/schema.rb#L134-L148 Database Schema 
.RE
.PP
\fBParameters\fP
.RS 4
\fI$Name\fP The name of a service 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 470 of file Phoenix\&.php\&.
.SS "static serviceExists (string $ID)\fC [static]\fP"
Check if a service exists by name 
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The ID of the service 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP
\fBDeprecated\fP
.RS 4
Use \fBPhoenix::serviceExistsPG\fP 
.RE
.PP

.PP
Definition at line 725 of file Phoenix\&.php\&.
.SS "static serviceExistsByName (string $Name)\fC [static]\fP"
Check if a service exists by name 
.PP
\fBParameters\fP
.RS 4
\fI$Name\fP The name of the service 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP
\fBDeprecated\fP
.RS 4
Use \fBPhoenix::serviceExistsByNamePG\fP 
.RE
.PP

.PP
Definition at line 637 of file Phoenix\&.php\&.
.SS "static serviceExistsByNamePG (string $Name)\fC [static]\fP"
Check if a service exists from postgres via name 
.PP
\fBParameters\fP
.RS 4
\fI$Name\fP The name of the service 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 607 of file Phoenix\&.php\&.
.SS "static serviceExistsBySlugPG (string $Name)\fC [static]\fP"
Check if a service exists from postgres via slug 
.PP
\fBParameters\fP
.RS 4
\fI$Name\fP The slug of the service 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 578 of file Phoenix\&.php\&.
.SS "static serviceExistsPG (string $ID)\fC [static]\fP"
Check if a service exists from postgres via the ID 
.PP
\fBParameters\fP
.RS 4
\fI$ID\fP The ID of the service 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 695 of file Phoenix\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
