.TH "ErrorReporter" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErrorReporter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBinitDB\fP ()"
.br
.ti -1c
.RI "static \fBcreate\fP (int $HttpStatusCode, string $Traceback, string $Summary, string $Prefix='ise_')"
.br
.in -1c
.SH "Detailed Description"
.PP 
The error reporting system 
.PP
Definition at line 30 of file ErrorReporter\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"

.PP
Definition at line 34 of file ErrorReporter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static create (int $HttpStatusCode, string $Traceback, string $Summary, string $Prefix = \fC'ise_'\fP)\fC [static]\fP"
Create a new Crash report 
.PP
\fBParameters\fP
.RS 4
\fI$HttpStatusCode\fP HTTP code 
.br
\fI$Traceback\fP A traceback e\&.g Exceptions 
.br
\fI$Summary\fP A summary of what happened 
.br
\fI$Prefix\fP of the reference id 
.RE
.PP
\fBReturns\fP
.RS 4
boolean|string Returns ReferenceID if successful otherwise false 
.RE
.PP

.PP
Definition at line 51 of file ErrorReporter\&.php\&.
.SS "static initDB ()\fC [static]\fP"

.PP
Definition at line 38 of file ErrorReporter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
