.TH "PluginAPI" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PluginAPI
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($PluginFolder, $PluginName, $Interface, $_QUERY)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBresponse\fP ($Errors, string $message, array $Parameters=[], $Flags=null, $HTTP=200)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$PluginFolder\fP"
.br
.ti -1c
.RI "\fB$PluginName\fP"
.br
.ti -1c
.RI "\fB$Interface\fP"
.br
.ti -1c
.RI "\fB$Query\fP"
.br
.ti -1c
.RI "\fB$PluginPath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used internally, plugin loader 
.PP
Definition at line 26 of file PluginAPI\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $PluginFolder,  $PluginName,  $Interface,  $_QUERY)"

.PP
\fBParameters\fP
.RS 4
\fI$PluginFolder\fP The path to your plugin 
.br
\fI$PluginName\fP The name of your plugin 
.br
\fI$PluginMetadata\fP Plugin\&.json file contents 
.br
\fI$TwigTheme\fP The current twig theme 
.br
\fI$CurrentFile\fP The current file 
.br
\fI$CurrentPage\fP The current $_GET['page'] parameter 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 46 of file PluginAPI\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static response ( $Errors, string $message, array $Parameters = \fC[]\fP,  $Flags = \fCnull\fP,  $HTTP = \fC200\fP)\fC [static]\fP"
Send a JSON response 
.PP
\fBParameters\fP
.RS 4
\fI$Errors\fP Error array or false 
.br
\fI$message\fP A message to send 
.br
\fI$Parameters\fP Some response parameters 
.br
\fI$Flags\fP JSON_ENCODE constants 
.RE
.PP

.PP
Definition at line 66 of file PluginAPI\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$Interface"

.PP
Definition at line 32 of file PluginAPI\&.php\&.
.SS "$PluginFolder"

.PP
Definition at line 30 of file PluginAPI\&.php\&.
.SS "$PluginName"

.PP
Definition at line 31 of file PluginAPI\&.php\&.
.SS "$PluginPath"

.PP
Definition at line 34 of file PluginAPI\&.php\&.
.SS "$Query"

.PP
Definition at line 33 of file PluginAPI\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
