.TH "Plugins" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Plugins
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBloadAPI\fP ($Interface, $_QUERY)"
.br
.ti -1c
.RI "static \fBlistPlugins\fP ()"
.br
.ti -1c
.RI "static \fBloadedPlugins\fP ()"
.br
.ti -1c
.RI "static \fBload\fP ($TwigTheme, $CurrentFile, $CurrentPage)"
.br
.ti -1c
.RI "static \fBmigrate\fP (string $PluginName)"
.br
.ti -1c
.RI "static \fBrefreshTranslations\fP ($PluginName, $PluginMetadata)"
.br
.ti -1c
.RI "static \fBrefreshKVStorage\fP ($PluginName, $PluginMetadata)"
.br
.ti -1c
.RI "static \fBinstallKVStorage\fP ($PluginName, $PluginMetadata)"
.br
.ti -1c
.RI "static \fBinstallTranslations\fP ($PluginName, $PluginMetadata)"
.br
.ti -1c
.RI "static \fBisInstalled\fP ($PluginName)"
.br
.ti -1c
.RI "static \fBisValid\fP ($PluginName)"
.br
.ti -1c
.RI "static \fBdeleteData\fP ($PluginName)"
.br
.ti -1c
.RI "static \fBtestVersion\fP ($VersionString)"
.br
.ti -1c
.RI "static \fBgetPluginMetadata\fP ($PluginName)"
.br
.ti -1c
.RI "static \fBuninstallCrons\fP ($PluginName, $PluginMetadata)"
.br
.ti -1c
.RI "static \fBinstallCrons\fP ($PluginName, $PluginMetadata)"
.br
.ti -1c
.RI "static \fBuninstallKVStorage\fP ($PluginName, $PluginMetadata)"
.br
.ti -1c
.RI "static \fBlistTranslations\fP ($PluginName)"
.br
.ti -1c
.RI "static \fBlistConfig\fP ($PluginName)"
.br
.ti -1c
.RI "static \fBuninstallTranslations\fP ($PluginName, $PluginMetadata)"
.br
.ti -1c
.RI "static \fBreinstall\fP ($PluginName, $TwigTheme, $CurrentFile, $CurrentPage)"
.br
.ti -1c
.RI "static \fBuninstall\fP ($PluginName, $TwigTheme, $CurrentFile, $CurrentPage)"
.br
.ti -1c
.RI "static \fBintegrityCheck\fP ($PluginName, $PluginMetadata)"
.br
.ti -1c
.RI "static \fBinstall\fP ($PluginName, $TwigTheme, $CurrentFile, $CurrentPage)"
.br
.ti -1c
.RI "static \fBregisterUninstallHook\fP ($PluginName, $Function)"
.br
.ti -1c
.RI "static \fBregisterAfterRenderHook\fP ($PluginName, $Function)"
.br
.ti -1c
.RI "static \fBregisterInstallHook\fP ($PluginName, $Function)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used internally, plugin loader 
.PP
Definition at line 26 of file Plugins\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static deleteData ( $PluginName)\fC [static]\fP"
Deletes all KVStorage Items from the \fBPlugin\fP
.PP
If the plugin is installed, it will get uninstalled first 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The folder name of the plugin 
.RE
.PP
\fBReturns\fP
.RS 4
boolean TRUE if the data has been successfully deleted 
.RE
.PP

.PP
Definition at line 348 of file Plugins\&.php\&.
.SS "static getPluginMetadata ( $PluginName)\fC [static]\fP"
Gets the decoded contents of the plugin\&.json 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The name of the plugin 
.RE
.PP
\fBReturns\fP
.RS 4
boolean 
.RE
.PP

.PP
Definition at line 397 of file Plugins\&.php\&.
.SS "static install ( $PluginName,  $TwigTheme,  $CurrentFile,  $CurrentPage)\fC [static]\fP"
Install a plugin and load it into the CMS @broadcasts pluginInstall 
.PP
\fBSee also\fP
.RS 4
\fBregisterInstallHook\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The Folder name of the \fBPlugin\fP 
.br
\fI$TwigTheme\fP The twig theme component 
.br
\fI$CurrentFile\fP The current file, \fBFILE\fP 
.br
\fI$CurrentPage\fP The current page template to render 
.RE
.PP
\fBReturns\fP
.RS 4
boolean TRUE if install was successful, otherwise FALSE 
.RE
.PP

.PP
Definition at line 709 of file Plugins\&.php\&.
.SS "static installCrons ( $PluginName,  $PluginMetadata)\fC [static]\fP"
Install all crons by plugin 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The name of the plugin 
.br
\fI$PluginMetadata\fP plugin\&.json contents decoded 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 432 of file Plugins\&.php\&.
.SS "static installKVStorage ( $PluginName,  $PluginMetadata)\fC [static]\fP"
Install storage from plugin\&.json 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The name of the plugin 
.br
\fI$PluginMetadata\fP plugin\&.json contents decoded 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 207 of file Plugins\&.php\&.
.SS "static installTranslations ( $PluginName,  $PluginMetadata)\fC [static]\fP"
Install all translations from plugin\&.json 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The name of the plugin 
.br
\fI$PluginMetadata\fP plugin\&.json contents decoded 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 247 of file Plugins\&.php\&.
.SS "static integrityCheck ( $PluginName,  $PluginMetadata)\fC [static]\fP"
Check if the integrity of a plugin is still fine 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The name of the plugin 
.br
\fI$PluginMetadata\fP Decoded plugin\&.json contents 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 627 of file Plugins\&.php\&.
.SS "static isInstalled ( $PluginName)\fC [static]\fP"
Checks if the specified plugin is installed 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The folder name of the plugin 
.RE
.PP
\fBReturns\fP
.RS 4
boolean TRUE if plugin is installed, otherwise FALSE 
.RE
.PP

.PP
Definition at line 326 of file Plugins\&.php\&.
.SS "static isValid ( $PluginName)\fC [static]\fP"

.PP
Definition at line 336 of file Plugins\&.php\&.
.SS "static listConfig ( $PluginName)\fC [static]\fP"
List all storage items by plugins 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The name of the plugin 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 510 of file Plugins\&.php\&.
.SS "static listPlugins ()\fC [static]\fP"
List all uninstalled plugins 
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 63 of file Plugins\&.php\&.
.SS "static listTranslations ( $PluginName)\fC [static]\fP"
List all translations by plugin 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The name of the plugin 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 492 of file Plugins\&.php\&.
.SS "static load ( $TwigTheme,  $CurrentFile,  $CurrentPage)\fC [static]\fP"
Load all plugins and check for matching templates 
.PP
\fBParameters\fP
.RS 4
\fI$TwigTheme\fP The twig theme component 
.br
\fI$CurrentFile\fP The current file, \fBFILE\fP 
.br
\fI$CurrentPage\fP The current page template to render 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 101 of file Plugins\&.php\&.
.SS "static loadAPI ( $Interface,  $_QUERY)\fC [static]\fP"
Load API files and check if plugin matches it\&. 
.PP
\fBParameters\fP
.RS 4
\fI$Interface\fP The interface we are listening on 
.br
\fI$_QUERY\fP The query 
.RE
.PP

.PP
Definition at line 35 of file Plugins\&.php\&.
.SS "static loadedPlugins ()\fC [static]\fP"
List all installed plugins 
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 82 of file Plugins\&.php\&.
.SS "static migrate (string $PluginName)\fC [static]\fP"

.PP
Definition at line 153 of file Plugins\&.php\&.
.SS "static refreshKVStorage ( $PluginName,  $PluginMetadata)\fC [static]\fP"
Reinstall all storage items 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The name of the plugin 
.br
\fI$PluginMetadata\fP plugin\&.json contents decoded 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP
\fBDeprecated\fP
.RS 4
0\&.0\&.8-beta\&.RC4 Use self::installKVStorage 
.RE
.PP

.PP
Definition at line 196 of file Plugins\&.php\&.
.SS "static refreshTranslations ( $PluginName,  $PluginMetadata)\fC [static]\fP"
Reinstall all translations 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The name of the plugin 
.br
\fI$PluginMetadata\fP plugin\&.json contents decoded 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP
\fBDeprecated\fP
.RS 4
0\&.0\&.8-beta\&.RC4 Use self::installTranslations 
.RE
.PP

.PP
Definition at line 184 of file Plugins\&.php\&.
.SS "static registerAfterRenderHook ( $PluginName,  $Function)\fC [static]\fP"

.PP
Definition at line 764 of file Plugins\&.php\&.
.SS "static registerInstallHook ( $PluginName,  $Function)\fC [static]\fP"
Registers an install hook for your plugin\&. 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP 
.br
\fI$Function\fP Callback function, either anonymous or a string to a function 
.RE
.PP
\fBReturns\fP
.RS 4
boolean TRUE if hook could be registered, otherwise false 
.RE
.PP

.PP
Definition at line 778 of file Plugins\&.php\&.
.SS "static registerUninstallHook ( $PluginName,  $Function)\fC [static]\fP"
Registers an uninstall hook for your plugin\&. 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP 
.br
\fI$Function\fP Callback function, either anonymous or a string to a function 
.RE
.PP
\fBReturns\fP
.RS 4
boolean TRUE if hook could be registered, otherwise false 
.RE
.PP

.PP
Definition at line 756 of file Plugins\&.php\&.
.SS "static reinstall ( $PluginName,  $TwigTheme,  $CurrentFile,  $CurrentPage)\fC [static]\fP"
Reinstall a plugin 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The name of the plugin 
.br
\fI$TwigTheme\fP The twig theme component 
.br
\fI$CurrentFile\fP The current file, \fBFILE\fP 
.br
\fI$CurrentPage\fP The current page template to render 
.RE
.PP
\fBReturns\fP
.RS 4
boolean 
.RE
.PP

.PP
Definition at line 571 of file Plugins\&.php\&.
.SS "static testVersion ( $VersionString)\fC [static]\fP"
Compare the current version of crisp with a custom version string 
.PP
\fBParameters\fP
.RS 4
\fI$VersionString\fP The semantic version string 
.RE
.PP
\fBSee also\fP
.RS 4
version_compare 
.RE
.PP
\fBReturns\fP
.RS 4
bool|int 
.RE
.PP

.PP
Definition at line 373 of file Plugins\&.php\&.
.SS "static uninstall ( $PluginName,  $TwigTheme,  $CurrentFile,  $CurrentPage)\fC [static]\fP"
Uninstall a plugin and prevent it from loading @broadcasts pluginUninstall 
.PP
\fBSee also\fP
.RS 4
\fBregisterUninstallHook\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The Folder name of the \fBPlugin\fP 
.br
\fI$TwigTheme\fP The twig theme component 
.br
\fI$CurrentFile\fP The current file, \fBFILE\fP 
.br
\fI$CurrentPage\fP The current page template to render 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 588 of file Plugins\&.php\&.
.SS "static uninstallCrons ( $PluginName,  $PluginMetadata)\fC [static]\fP"
Uninstall all crons by plugin 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The name of the plugin 
.br
\fI$PluginMetadata\fP plugin\&.json contents decoded 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 413 of file Plugins\&.php\&.
.SS "static uninstallKVStorage ( $PluginName,  $PluginMetadata)\fC [static]\fP"
uninstall all storage items by plugin 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The name of the plugin 
.br
\fI$PluginMetadata\fP plugin\&.json contents decoded 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 460 of file Plugins\&.php\&.
.SS "static uninstallTranslations ( $PluginName,  $PluginMetadata)\fC [static]\fP"
Uninstall all translations by plugin 
.PP
\fBParameters\fP
.RS 4
\fI$PluginName\fP The name of the plugin 
.br
\fI$PluginMetadata\fP plugin\&.json contents decoded 
.RE
.PP
\fBReturns\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 530 of file Plugins\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
