.TH "crisp" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crisp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBapi\fP"
.br
.ti -1c
.RI " \fBcore\fP"
.br
.ti -1c
.RI " \fBexceptions\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBUniverse\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
