.TH "crisp\api" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crisp\api
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlists\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAPIStats\fP"
.br
.ti -1c
.RI "class \fBConfig\fP"
.br
.ti -1c
.RI "class \fBErrorReporter\fP"
.br
.ti -1c
.RI "class \fBHelper\fP"
.br
.ti -1c
.RI "class \fBLanguage\fP"
.br
.ti -1c
.RI "class \fBPhoenix\fP"
.br
.ti -1c
.RI "class \fBTranslation\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
