.TH "Config" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBexists\fP ($Key)"
.br
.ti -1c
.RI "static \fBget\fP ($Key)"
.br
.ti -1c
.RI "static \fBgetTimestamp\fP (string $Key)"
.br
.ti -1c
.RI "static \fBcreate\fP ($Key, $Value)"
.br
.ti -1c
.RI "static \fBdelete\fP ($Key)"
.br
.ti -1c
.RI "static \fBset\fP ($Key, $Value)"
.br
.ti -1c
.RI "static \fBlist\fP ($KV=false)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interact with the key/value storage of the server 
.PP
Definition at line 30 of file Config\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static create ( $Key,  $Value)\fC [static]\fP"
Create a new KV Storage entry using the specified key and value 
.PP
\fBParameters\fP
.RS 4
\fI$Key\fP the key to insert 
.br
\fI$Value\fP the value to insert 
.RE
.PP
\fBReturns\fP
.RS 4
boolean TRUE on success, on failure FALSE 
.RE
.PP

.PP
Definition at line 116 of file Config\&.php\&.
.SS "static delete ( $Key)\fC [static]\fP"
Delete a KV Storage entry using the specified key 
.PP
\fBParameters\fP
.RS 4
\fI$Key\fP the key to insert 
.RE
.PP
\fBReturns\fP
.RS 4
boolean TRUE on success, on failure FALSE 
.RE
.PP

.PP
Definition at line 135 of file Config\&.php\&.
.SS "static exists ( $Key)\fC [static]\fP"
Checks if a Storage items exists using the specified key 
.PP
\fBParameters\fP
.RS 4
\fI$Key\fP the key to retrieve from the KV \fBConfig\fP from 
.RE
.PP
\fBReturns\fP
.RS 4
boolean TRUE if it exists, otherwise FALSE 
.RE
.PP

.PP
Definition at line 44 of file Config\&.php\&.
.SS "static get ( $Key)\fC [static]\fP"
Retrieves a value from the KV Storage using the specified key 
.PP
\fBParameters\fP
.RS 4
\fI$Key\fP the key to retrieve from the KV \fBConfig\fP from 
.RE
.PP
\fBReturns\fP
.RS 4
string|boolean The value as string, on failure FALSE 
.RE
.PP

.PP
Definition at line 61 of file Config\&.php\&.
.SS "static getTimestamp (string $Key)\fC [static]\fP"
Get the timestamps of a key 
.PP
\fBParameters\fP
.RS 4
\fI$Key\fP The KVStorage key 
.RE
.PP
\fBReturns\fP
.RS 4
array Containing last_changed, created_at 
.RE
.PP

.PP
Definition at line 94 of file Config\&.php\&.
.SS "static list ( $KV = \fCfalse\fP)\fC [static]\fP"
Returns all keys and values from the KV Storage 
.PP
\fBParameters\fP
.RS 4
\fI$KV\fP List keys as associative array? 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 181 of file Config\&.php\&.
.SS "static set ( $Key,  $Value)\fC [static]\fP"
Updates a value for a key in the KV Storage 
.PP
\fBParameters\fP
.RS 4
\fI$Key\fP Existing key to change the value from 
.br
\fI$Value\fP The value to set 
.RE
.PP
\fBReturns\fP
.RS 4
boolean TRUE on success, otherwise FALSE 
.RE
.PP

.PP
Definition at line 149 of file Config\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
