.TH "Universe" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Universe
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBchangeUniverse\fP ($\fBUniverse\fP, $Authorize=false)"
.br
.ti -1c
.RI "static \fBgetUniverse\fP ($\fBUniverse\fP)"
.br
.ti -1c
.RI "static \fBgetUniverseName\fP ($value)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBUNIVERSE_PUBLIC\fP = 1"
.br
.ti -1c
.RI "const \fBUNIVERSE_BETA\fP = 2"
.br
.ti -1c
.RI "const \fBUNIVERSE_DEV\fP = 3"
.br
.ti -1c
.RI "const \fBUNIVERSE_TOSDR\fP = 99"
.br
.in -1c
.SH "Detailed Description"
.PP 
Crisp \fBUniverse\fP Handling 
.PP
Definition at line 25 of file Universe\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static changeUniverse ( $Universe,  $Authorize = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 32 of file Universe\&.php\&.
.SS "static getUniverse ( $Universe)\fC [static]\fP"

.PP
Definition at line 39 of file Universe\&.php\&.
.SS "static getUniverseName ( $value)\fC [static]\fP"

.PP
Definition at line 54 of file Universe\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const UNIVERSE_BETA = 2"

.PP
Definition at line 28 of file Universe\&.php\&.
.SS "const UNIVERSE_DEV = 3"

.PP
Definition at line 29 of file Universe\&.php\&.
.SS "const UNIVERSE_PUBLIC = 1"

.PP
Definition at line 27 of file Universe\&.php\&.
.SS "const UNIVERSE_TOSDR = 99"

.PP
Definition at line 30 of file Universe\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
