.TH "Config" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fB$Cookie_Prefix\fP = 'crisp_'"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class holds the cookie prefix and mysql constants 
.PP
Definition at line 26 of file Config\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$Cookie_Prefix = 'crisp_'\fC [static]\fP"

.PP
Definition at line 32 of file Config\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
