.TH "ErrorReporter" 3 "Sat Dec 26 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErrorReporter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBinitDB\fP ()"
.br
.ti -1c
.RI "static \fBcreate\fP ($HttpStatusCode, $Traceback, $Summary)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The error reporting system, currently unused\&. 
.PP
\fBDeprecated\fP
.RS 4
It's unused 
.RE
.PP

.PP
Definition at line 31 of file ErrorReporter\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"

.PP
Definition at line 35 of file ErrorReporter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static create ( $HttpStatusCode,  $Traceback,  $Summary)\fC [static]\fP"

.PP
Definition at line 44 of file ErrorReporter\&.php\&.
.SS "static initDB ()\fC [static]\fP"

.PP
Definition at line 39 of file ErrorReporter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
