.TH "MySQL" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySQL
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBgetDBConnector\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interact with the database yourself\&. Please use this interface only when you REALLY need it for custom tables\&. We offer a variety of functions to interact with users or the system itself in a safe way :-) 
.PP
Definition at line 28 of file MySQL\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"
Constructs the Database_Connection 
.PP
\fBSee also\fP
.RS 4
\fBgetDBConnector\fP 
.RE
.PP

.PP
Definition at line 36 of file MySQL\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getDBConnector ()"
Get the database connector 
.PP
\fBReturns\fP
.RS 4
PDO 
.RE
.PP

.PP
Definition at line 49 of file MySQL\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
