.TH "pixelcatproductions/class/crisp/api/lists/Cron.php" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixelcatproductions/class/crisp/api/lists/Cron.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCron\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBcrisp\\api\\lists\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CrispCMS Plugin API from the source code\&.
