.TH "deprecated" 3 "Mon Dec 28 2020" "CrispCMS Plugin API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBGlobal \fBPhoenix::getPoint\fP (string $ID, bool $Force=false)\fP" 1c
Use \fBPhoenix::getPointPG\fP  
.IP "\fBGlobal \fBPhoenix::getCase\fP (string $ID, bool $Force=false)\fP" 1c
Use \fBPhoenix::getCasePG\fP  
.IP "\fBGlobal \fBPhoenix::getTopic\fP (string $ID, bool $Force=false)\fP" 1c
Use \fBPhoenix::getTopicPG\fP  
.IP "\fBGlobal \fBPhoenix::getServiceByName\fP (string $Name, bool $Force=false)\fP" 1c
Use \fBPhoenix::getServiceByNamePG\fP  
.IP "\fBGlobal \fBPhoenix::serviceExistsByName\fP (string $Name)\fP" 1c
Use \fBPhoenix::serviceExistsByNamePG\fP  
.IP "\fBGlobal \fBPhoenix::pointExists\fP (string $ID)\fP" 1c
Use \fBPhoenix::pointExistsPG\fP  
.IP "\fBGlobal \fBPhoenix::serviceExists\fP (string $ID)\fP" 1c
Use \fBPhoenix::serviceExistsPG\fP  
.IP "\fBGlobal \fBPhoenix::getService\fP (string $ID, bool $Force=false)\fP" 1c
Use \fBPhoenix::getServicePG\fP  
.IP "\fBGlobal \fBPhoenix::getTopics\fP (bool $Force=false)\fP" 1c
Use \fBPhoenix::getServicesPG\fP  
.IP "\fBGlobal \fBPhoenix::getCases\fP (bool $Force=false)\fP" 1c
Use \fBPhoenix::getCasesPG\fP  
.IP "\fBGlobal \fBPhoenix::getServices\fP (bool $Force=false)\fP" 1c
Please use \fBPhoenix::getServicesPG\fP  
.IP "\fBGlobal \fBPlugins::refreshTranslations\fP ($PluginName, $PluginMetadata)\fP" 1c
0\&.0\&.8-beta\&.RC4 Use self::installTranslations  
.IP "\fBGlobal \fBPlugins::refreshKVStorage\fP ($PluginName, $PluginMetadata)\fP" 1c
0\&.0\&.8-beta\&.RC4 Use self::installKVStorage 
.PP

